apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:devops, applications, sync, *, allow
    p, role:devops, applications, get, *, allow
    g, harshad, role:devops
