apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.northbay.com
  admin.enabled: "false"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $dex.github.clientId
          clientSecret: $dex.github.clientSecret
          orgs:
            - name: northbay
  resource.exclusions: |
    - apiGroups:
        - "*.k8s.io"
      kinds:
        - Event
      clusters:
        - "*"
