name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

variables:
- group: global-variables
- name: azureSubscription
  value: AzureSubscription
- name: acrName
  value: northbay
- name: imageName
  value: dubai-realestate-ml
- name: imageTag
  value: $(Build.BuildId)
- name: helmChartPath
  value: chart/
- name: aksResourceGroup
  value: aks-private-rg
- name: aksClusterName
  value: aks-private-cluster

pool:
  name: SelfHosted-Private  
  demands: azurecli

stages:
- stage: Setup_ArgoCD
  displayName: Install and Configure Argo CD
  jobs:
  - job: Install_ArgoCD
    displayName: Install ArgoCD into AKS
    steps:
    - checkout: self
      persistCredentials: true
    - task: AzureCLI@2
      displayName: Install / Configure Argo CD
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --overwrite-existing

          if kubectl get ns argocd >/dev/null 2>&1; then
            echo "Argo CD namespace already exists."
          else
            kubectl create namespace argocd
            kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
            kubectl wait --for=condition=Ready pods -l app.kubernetes.io/name=argocd-server -n argocd --timeout=300s || true
          fi

          # Apply ArgoCD configuration patches
          if [ -f "argocd/patches/argocd-cm.yaml" ]; then
            kubectl apply -f argocd/patches/argocd-cm.yaml
          fi
          if [ -f "argocd/patches/argocd-rbac-cm.yaml" ]; then
            kubectl apply -f argocd/patches/argocd-rbac-cm.yaml
          fi
          
          # Create ArgoCD project
          if [ -f "argocd/project.yaml" ]; then
            kubectl apply -f argocd/project.yaml
          fi
          
          # Create repository secret for Git access
          if [ -f "argocd/repo-secret.yaml" ]; then
            kubectl apply -f argocd/repo-secret.yaml
          fi
          
          # Apply ArgoCD Application
          if [ -f "argocd/app-bluegreen.yaml" ]; then
            kubectl apply -f argocd/app-bluegreen.yaml
          fi

          kubectl rollout status deployment/argocd-server -n argocd || true

- stage: Prepare_Terraform_Values
  displayName: Prepare Helm Values from Terraform Outputs
  dependsOn: Setup_ArgoCD
  jobs:
  - job: Prepare_Values
    displayName: Generate Helm Values from Terraform
    steps:
    - checkout: self
      persistCredentials: true
    - task: AzureCLI@2
      displayName: Get Terraform Outputs and Generate Values
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          # Navigate to terraform directory
          cd terraform
          
          # Initialize Terraform (if not already done)
          terraform init \
            -backend-config="resource_group_name=$(terraformBackendResourceGroupName)" \
            -backend-config="storage_account_name=$(terraformBackendStorageAccountName)" \
            -backend-config="container_name=$(terraformBackendContainerName)" \
            -backend-config="key=infra.tfstate" \
            -backend-config="access_key=$(terraformBackendStorageAccountKey)" || true
          
          # Get Terraform outputs
          TENANT_ID=$(terraform output -raw tenant_id)
          KEY_VAULT_NAME=$(terraform output -raw key_vault_name)
          WORKLOAD_IDENTITY_CLIENT_ID=$(terraform output -raw aks_workload_identity_client_id)
          
          # Generate values file
          cat > ../chart/values-terraform.yaml <<EOF
          terraformConfig:
            enabled: true
            tenantId: "$TENANT_ID"
            keyVaultName: "$KEY_VAULT_NAME"
            workloadIdentityClientId: "$WORKLOAD_IDENTITY_CLIENT_ID"
          
          keyVault:
            enabled: true
            name: "$KEY_VAULT_NAME"
            tenantId: "$TENANT_ID"
          EOF
          
          echo "Generated values-terraform.yaml with Terraform outputs"
          echo "Tenant ID: $TENANT_ID"
          echo "Key Vault Name: $KEY_VAULT_NAME"

- stage: Build_and_Push
  displayName: Build and Push Docker Image
  dependsOn: Prepare_Terraform_Values
  jobs:
  - job: Build
    steps:
    - checkout: self
      persistCredentials: true
    - task: AzureCLI@2
      displayName: Build and Push to ACR
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(acrName)
          docker build -t $(acrName).azurecr.io/$(imageName):$(imageTag) .
          docker push $(acrName).azurecr.io/$(imageName):$(imageTag)
          echo "##vso[task.setvariable variable=imageFullPath;]$(acrName).azurecr.io/$(imageName):$(imageTag)"

- stage: Update_Git_and_Trigger_Argo
  displayName: Update Helm values.yaml and Trigger ArgoCD Sync
  dependsOn: Build_and_Push
  jobs:
  - job: GitUpdate
    steps:
    - checkout: self
      persistCredentials: true
    - bash: |
        set -e
        # Update image tag
        sed -i "s|tag:.*|tag: $(imageTag)|" $(helmChartPath)/values.yaml
        
        # Merge Terraform-generated values if they exist
        if [ -f "$(helmChartPath)/values-terraform.yaml" ]; then
          echo "Merging Terraform-generated values..."
          # Use yq or a simple merge approach
          # For now, we'll ensure values-terraform.yaml is also committed
          git add $(helmChartPath)/values-terraform.yaml || true
        fi
        
        git config user.email "buildagent@azuredevops.local"
        git config user.name "Azure DevOps Pipeline"
        git add $(helmChartPath)/values.yaml
        git commit -m "Auto: update image tag to $(imageTag)" || echo "No changes to commit."
        git push origin main

- stage: Flip_Service
  displayName: Switch Traffic Between Blue and Green
  dependsOn: Update_Git_and_Trigger_Argo
  jobs:
  - job: Flip
    steps:
    - checkout: self
      persistCredentials: true
    - bash: |
        set -e
        CURRENT=$(grep activeVersion: $(helmChartPath)/values.yaml | awk '{print $2}')
        if [ "$CURRENT" = "blue" ]; then
          NEXT="green"
        else
          NEXT="blue"
        fi
        sed -i "s|activeVersion:.*|activeVersion: $NEXT|" $(helmChartPath)/values.yaml
        git config user.email "buildagent@azuredevops.local"
        git config user.name "Azure DevOps Pipeline"
        git add $(helmChartPath)/values.yaml
        git commit -m "Switch traffic to $NEXT after successful deployment" || echo "No changes to commit."
        git push origin main
