apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dubai-realestate-ml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: slack
    notifications.argoproj.io/subscribe.on-sync-failed.slack: slack
spec:
  project: dubai-ml-project
  source:
    repoURL: git@github.com:harshadkhetpal/northbay-test.git
    targetRevision: main
    path: chart
    helm:
      valueFiles:
        - values.yaml
        - values-terraform.yaml
      releaseName: dubai-realestate-ml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - Replace=true  # Use replace instead of apply for faster syncs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore replica count (managed by HPA)
        - /metadata/annotations/prometheus.io~1scrape  # Ignore prometheus annotations
    - group: ""
      kind: Service
      jsonPointers:
        - /metadata/annotations
  info:
    - name: Description
      value: Dubai Real Estate ML Service - Blue-Green Deployment
    - name: Repository
      value: https://github.com/harshadkhetpal/northbay-test
